version: "3"

name: "simple-crud"

services:
  database:
    image: postgres:14
    container_name: dish-postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:
