version: "3"

name: "simple-crud"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dish-api
    env_file:
      - .env
    ports:
      - "3000:3000"
  database:
    image: postgres:14
    container_name: dish-postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"

volumes:
  postgres-data:
